package org.example.utils;
public enum TestScenarios {

    T1("Login Valid Functionality Test"),
    T2("Login Invalid Functionality Test (Input invalid username & Input invalid password)"),
    T3("Dashboard Valid Functionality Test"),
    T4("Enter Dashboard Employee"),
    T5("Check Total HO Overall Dashboard Aplikasi Sipanda-Unik"),
    T6("Check HO On Progress Dashboard Aplikasi Sipanda-Unik"),
    T7("Check HO Completed Dashboard Aplikasi Sipanda-Unik"),
    T8("Check Total Task Dashboard Aplikasi Sipanda-Unik"),
    T9("Check Task Has Not Proceed Dashboard Aplikasi Sipanda-Unik"),
    T10("Check Task Need Approval JP Dashboard Aplikasi Sipanda-Unik"),
    T11("Check Task Need Approval Partner Dashboard Aplikasi Sipanda-Unik"),
    T12("Check Task Finished Dashboard Aplikasi Sipanda-Unik"),
    T13("Check Total Activity Dashboard Aplikasi Sipanda-Unik"),
    T14("Check Activity Need Revision Dashboard Aplikasi Sipanda-Unik"),
    T15("Check Activity Need Approval JP Dashboard Aplikasi Sipanda-Unik"),
    T16("Check Task Need Approval Partner Dashboard Aplikasi Sipanda-Unik"),
    T17("Check Activity Finished Dashboard Aplikasi Sipanda-Unik"),
    T18("Proceed overdue deadline task Dashboard Aplikasi Sipanda-Unik"),
    T19("Proceed upcoming deadline task Dashboard Aplikasi Sipanda-Unik"),
    T20("Add event dashboard"),
    T21("Edit event dashboard"),
    T22("Enter HO Page"),
    T23("Create HO"),
    T24("User Search Valid Data Based ID HO"),
    T25("Enter HO Working Plan Page"),
    T26("Edit HO"),
    T27("Enter Detail Client Balance"),
    T28("Add Task"),
    T29("Add Activity"),
    T30("Edit Task"),
    T31("View Task"),
    T32("Complete The Task"),
    T33("JP Approval Task"),
    T34("Revision Task"),
    T35("Partner Approval Task"),
    T36("JP Approval Activity"),
    T37("Revision Activity"),
    T38("Partner Approval Activity"),
    T39("Create Document RKPD"),
    T40("JP Approval Document RKPD"),
    T41("Partner Approval Document RKPD"),
    T42("Create Document Surat Tugas"),
    T44("Create Document LKPD"),
    T45("JP Approval Document LKPD"),
    T46("Partner Approval Document LKPD"),
    T47("Create Document Reimbursement RKPD"),
    T48("JP Approval Document Reimbursement RKPD"),
    T49("Partner Approval Document Reimbursement RKPD"),
    T50("Create Document Trip Accommodation"),
    T51("JP Approval Document Trip Accommodation"),
    T52("Partner Approval Document Trip Accommodation"),
    T53("Enter Dashboard Employee"),
    T54("Create Document Disbursement Trip"),
    T55("JP Approval Document Disbursement Trip"),
    T56("Partner Approval Document Disbursement Trip"),
    T57("Create Document Deposit Receipt"),
    T58("View Document RKPD"),
    T59("View Document Surat Tugas"),
    T60("View Document Trip Accommodation"),
    T61("View Document Surat LKPD"),
    T62("View Document Surat Reimbursement RKPD"),
    T63("View Document Disbursement Trip"),
    T64("View Business Trip Recap"),
    T67("View Business Trip Expenses Recap"),
    T68("Edit Document Disbursement Trip"),
    T69("Delete Document Disbursement Trip"),
    T70("Edit Document Reimbursement RKPD"),
    T71("Delete Document Reimbursement RKPD"),
    T72("Edit Document Trip Accommodation"),
    T73("Delete Document Trip Accommodation"),
    T74("Edit Document LKPD"),
    T75("Delete Document LKPD"),
    T76("Edit Document Surat Tugas"),
    T77("Delete Document Surat Tugas"),
    T78("Edit Document RKPD"),
    T79("Delete Document RKPD"),
    T80("Upload Document HO Working Plan"),
    T81("Delete Upload Document HO Working Plan"),
    T82("Create Notulen HO Working Plan"),
    T83("Create HO Reimbursement HO Working Plan"),
    T84("Edit HO Reimbursement HO Working Plan"),
    T85("View HO Reimbursement HO Working Plan"),
    T86("JP Approval HO Reimbursement HO Working Plan"),
    T87("Delete HO Reimbursement HO Working Plan"),
    T88("Create HO Overtime HO Working Plan"),
    T89("Edit HO Overtime HO Working Plan"),
    T90("View HO Overtime HO Working Plan"),
    T91("JP Approval HO Overtime HO Working Plan"),
    T92("Delete HO Overtime HO Working Plan"),
    T93("View HO Activities HO Working Plan"),
    T94("Complete HO"),
    T95("Enter List Approval Page"),
    T96("JP Approval Task List Approval"),
    T97("Partner Approval Task List Approval"),
    T98("JP Approval RKPD List Approval"),
    T99("Partner Approval RKPD List Approval"),
    T100("JP Approval LKPD List Approval"),
    T101("Partner Approval LKPD List Approval"),
    T102("JP Approval Reimbursement RKPD List Approval"),
    T103("Partner Approval Reimbursement RKPD List Approval"),
    T104("JP Approval Disbursement Trip List Approval"),
    T105("Partner Approval Disbursement Trip List Approval"),
    T106("JP Approval Trip Accommodation List Approval"),
    T107("Partner Approval Trip Accommodation List Approval"),
    T108("JP Approval HO Reimbursement List Approval"),
    T109("FD Approval HO Reimbursement List Approval"),
    T110("Partner Approval HO Overtime List Approval"),
    T111("Enter Calendar Page"),
    T112("Enter Finance Page"),
    T113("Enter HO Report Finance Page"),
    T114("Download Excel & PDF HO Report Finance"),
    T115("Enter Task & Activity Report Finance Page"),
    T116("Download Excel & PDF Task & Activity Report Finance"),
    T117("Enter Task & Activity Summary Report Finance Page"),
    T118("Download Excel & PDF Task & Activity Summary Report Finance"),
    T119("Enter Client Report Finance Page"),
    T120("Download Excel & PDF Client Report Finance"),
    T121("Enter Administrative Report Finance Page"),
    T122("Download Excel & PDF Administrative Report Finance"),
    T123("Enter Administrative Summary Report Finance Page"),
    T124("Download Excel & PDF Administrative Summary Report Finance"),
    T125("Enter Administrative Approval Report Finance Page"),
    T126("Download Excel & PDF Administrative Approval Report Finance"),
    T127("Enter HO Reimbursement Finance Page"),
    T128("Download Excel HO Reimbursement Report Finance"),
    T129("Enter Finance Report Page"),
    T130("Download Excel Finance Reimbursement Report"),
    T131("Enter Finance Master Document Number Report Page"),
    T132("Download Excel Finance Master Document Number Report"),
    T133("Enter Finance Payroll Report Page"),
    T134("Download Excel Finance Payroll Report"),
    T135("Enter HO Deposit Report Page"),
    T136("Download Excel HO Deposit Report"),
    T137("Enter HO Deposit Receipt Report Page"),
    T138("Download Excel HO Deposit Receipt Report"),
    T139("Enter HO Business Trip Reimbursement Report Page"),
    T140("Download Excel HO Business Trip Reimbursement Report"),
    T141("Enter Finance General Ledger Report Page"),
    T142("Download Excel Finance General Ledger Report"),
    T143("Enter Client Page"),
    T144("Add Client"),
    T145("Edit Client"),
    T146("Delete Client"),
    T147("Enter HO Completed Page"),
    T148("View HO Completed Page"),
    T149("Restore Completed HO"),
    T150("Enter Finance Document Page"),
    T151("Edit Finance Document Number"),
    T152("Delete Finance Document Number"),
    T153("Enter Finance List Document Page"),
    T154("Create Finance List Document"),
    T155("Upload document Finance List Document"),
    T156("Edit Finance List Document"),
    T157("Delete Finance List Document"),
    T158("Enter Finance Payroll Page"),
    T159("Create Finance Payroll Periode"),
    T160("Enter Finance Detail Periode Payroll"),
    T161("Edit Finance Payroll Employee"),
    T162("Delete Finance Payroll Periode"),
    T163("Enter Finance Reimbursement Page"),
    T164("Create Finance Reimbursement"),
    T165("Edit Finance Reimbursement"),
    T167("View Finance Reimbursement"),
    T168("Approval Finance Reimbursement"),
    T169("Delete Finance Reimbursement"),
    T170("Enter HO Reimbursement Payment Page"),
    T171("Proceed Payment HO Reimbursement"),
    T172("Edit Payment HO Reimbursement"),
    T173("Approval Payment HO Reimbursement"),
    T174("View Approved Payment HO Reimbursement"),
    T175("Enter Finance Reimbursement Payment Page"),
    T176("Proceed Payment Finance Reimbursement"),
    T177("Edit Payment Finance Reimbursement"),
    T178("Approval Payment Finance Reimbursement"),
    T179("View Approved Payment Finance Reimbursement"),
    T180("Enter Disbursement Trip Payment Page"),
    T181("Proceed Payment Disbursement Trip"),
    T182("Edit Payment Disbursement Trip"),
    T183("Approval Payment Disbursement Trip"),
    T184("View Approved Payment Disbursement Trip"),
    T185("Enter HR Page"),
    T186("Enter Attendance Page"),
    T187("Search Employee Attendance by Name"),
    T188("Enter Monitoring Page"),
    T189("Search Employee Monitoring by Name"),
    T190("Enter HR Report Page"),
    T191("Download KPI HO Report"),
    T192("Download KPI HO Detail Report"),
    T193("Download Excel & PDF Daily Report"),
    T194("Download Resume Daily Report"),
    T195("Download HR Master Document Number Report"),
    T196("Enter Overtime Page"),
    T197("Create Overtime"),
    T198("Edit Overtime"),
    T199("Approval Overtime"),
    T200("View Approved Overtime Page"),
    T201("Download Preview Overtime"),
    T202("Download Overtime Report"),
    T203("Enter Log User Page"),
    T204("Search Log User by Employee Name"),
    T205("Download Excel & PDF Log User Report"),
    T206("Enter Workload Page"),
    T207("Download Excel & PDF Workload Report"),
    T208("Enter Leave Permission Page"),
    T209("Create Leave Permission"),
    T210("Edit Leave Permission"),
    T211("Approval Leave Permission"),
    T212("View Approved Leave Permission Page"),
    T213("Download Preview Leave Permission"),
    T214("Download Leave Permission Report"),
    T215("Enter Joint Holiday Page"),
    T216("Create Joint Holiday"),
    T217("Edit Joint Holiday"),
    T218("Delete Joint Holiday"),
    T219("Enter Master Holiday Page"),
    T220("Edit Master Holiday"),
    T221("Search Master Holiday"),
    T222("Enter Employee Page"),
    T223("Search Employee by Name"),
    T224("Filter Employee by Status"),
    T225("Create Employee"),
    T226("Edit Role Data Employee"),
    T227("Edit Personal Data Employee"),
    T228("Edit Family Data Employee"),
    T229("Edit Employee Data Employee"),
    T230("Edit Operational Data Employee"),
    T231("Delete Employee"),
    T232("Enter Master Input Page"),
    T233("Create Company"),
    T234("Search Company by ID Company"),
    T235("Edit Company Data"),
    T236("Delete Company"),
    T237("Create Office Location"),
    T238("Search Office Location by ID Office Location"),
    T239("Edit Office Location Data"),
    T240("Delete Office Location"),
    T241("Create Department"),
    T242("Search Department by ID Department"),
    T243("Edit Department Data"),
    T244("Delete Department"),
    T245("Create Position"),
    T246("Search Position by ID Position"),
    T247("Edit Position Data"),
    T248("Delete Position"),
    T249("Create Region"),
    T250("Search Region by ID Region"),
    T251("Edit Region Data"),
    T252("Delete Region"),
    T253("Create SOW"),
    T254("Search SOW by SOW Name"),
    T255("Edit SOW"),
    T256("Create SOW Tree & Score"),
    T257("Edit SOW Tree & Score Data"),
    T258("Download Template SOW"),
    T259("Download SOW Tree & Score"),
    T260("Create Type of Client"),
    T261("Search Type of Client by Type of Client Name"),
    T262("Edit Type of Client"),
    T263("Delete Type of Client"),
    T264("Create Grade"),
    T265("Search Grade by ID Grade"),
    T266("Edit Court Money Grade"),
    T267("Edit Allowance Grade"),
    T268("Edit Meal Allowance Grade"),
    T269("Edit Professional Fee Grade"),
    T270("Edit Hotel Grade"),
    T271("Edit Flight Grade"),
    T272("Delete Grade"),
    T273("Create Type of Leave"),
    T274("Search Type of Leave by Type of Leave Name"),
    T275("Edit Type of Leave Data"),
    T276("Delete type of Leave"),
    T277("Edit Overtime Data"),
    T278("Create Mandatory Deductions"),
    T279("Search Mandatory Deductions by ID Mandatory Deductions"),
    T280("Add Employee Mandatory Deductions"),
    T281("Edit Mandatory Deductions Data"),
    T282("Delete Mandatory Deductions"),
    T283("Create PPH21"),
    T284("Search PPH21 by Name PPH21"),
    T285("Add Employee PPH21"),
    T286("Edit PPH21 Data"),
    T287("Delete PPH21"),
    T288("Create Shifting"),
    T289("Search Shifting by Shift Name"),
    T290("Add Employee Shifting"),
    T291("Edit Shifting Data"),
    T292("Delete Shifting"),
    T293("Create Running Text"),
    T294("Search Running Text by ID Runnging Text"),
    T295("Edit Running Text"),
    T296("Delete Running Text"),
    T297("Enter HR Document Page"),
    T298("Create HR Document Number"),
    T299("Edit HR Document Number Data"),
    T300("Delete HR Document Number"),
    T301("Enter HR List Document Page"),
    T302("Create HR List Document"),
    T303("Upload document HR List Document"),
    T304("Edit HR List Document"),
    T305("Delete HR List Document"),
    T306("Enter HR Request Letter Page"),
    T307("Create HR Request Letter"),
    T308("Edit HR Request Letter"),
    T309("Approval HR Request Letter"),
    T310("View Approved HR Request Letter"),
    T311("Enter GA Dashboard Page"),
    T312("Enter GA Report Page"),
    T313("Download Maintenance Report"),
    T314("Download Asset Report"),
    T315("Download Stock Consumable Report"),
    T316("Download Moving Stock Report"),
    T317("Download GA Master Document Number Report"),
    T318("Enter Master GA Page"),
    T319("Create Master GA Category"),
    T320("Edit Master GA Category Data"),
    T321("View Master GA Category"),
    T322("Delete Master GA Category"),
    T323("Create Master GA Brand"),
    T324("Edit Master GA Brand Data"),
    T325("View Master GA Brand"),
    T326("Delete Master GA Brand"),
    T327("Create Master GA Type"),
    T328("Edit Master GA Type Data"),
    T329("View Master GA Type"),
    T330("Delete Master GA Type"),
    T331("Enter Asset Data Page"),
    T332("Create Asset Data"),
    T333("Edit Asset Data"),
    T334("View Asset Data"),
    T335("Delete Asset Data"),
    T336("Enter Asset Maintenance Page"),
    T337("Create Asset Maintenance"),
    T338("Edit Asset Maintenance Data"),
    T339("Delete Asset Maintenance"),
    T340("Enter Master Consumable Page"),
    T341("Add Master Consumable"),
    T342("View Master Consumable"),
    T343("Enter Consumable Page"),
    T344("Add Stock Consumable"),
    T345("Edit Add Stock Consumable Data"),
    T346("Add Consume Data"),
    T347("Add Moving Stock Data"),
    T348("Enter GA Document Page"),
    T349("Create GA Document Number"),
    T350("Edit GA Document Number Data"),
    T351("Delete GA Document Number"),
    T352("Enter GA List Document Page"),
    T353("Create GA List Document"),
    T354("Upload document GA List Document"),
    T355("Edit GA List Document"),
    T356("Delete GA List Document"),
    T357("Enter Document Dashboard Page"),
    T358("Enter Document Report Page"),
    T359("Download Document Master Document Number Report"),
    T360("Enter Document Number Page"),
    T361("Create Document Number"),
    T362("Edit Document Number Data"),
    T363("Delete Document Number"),
    T364("Enter List Document Page"),
    T365("Create List Document"),
    T366("Upload document List Document"),
    T367("Edit List Document Data"),
    T368("Delete List Document"),
    T369("Enter Procurement Dashboard Page"),
    T370("Enter Procurement Report Page"),
    T371("Download Request Order Report"),
    T372("Download Request Order Complete Report"),
    T373("Enter Request Order Page"),
    T374("Create Request Order"),
    T375("Edit Request Order Data"),
    T376("Approval Financial Director Request Order"),
    T377("Approval Director Request Order"),
    T378("Upload Receipt Payment Request Order"),
    T379("Upload Receipt Paid Payment Request Order"),
    T380("Complete Request Order"),
    T381("Enter Request Order Complete Page"),
    T382("View Request Order Completed"),
    T383("Logout Sipanda Unik");









    private final String testCaseName;

    TestScenarios(String value) {
        testCaseName = value;
    }

    public String getTestCaseName() {
        return testCaseName;
    }
}
